In [2]:
import numpy as np



1. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули.




In [4]:
c = np.vstack(( np.zeros(4), np.diag([1, 2, 3 , 4])))
b = np.zeros(5).reshape(-1, 1)
c = np.hstack((c, b))
print(c)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


2.Создайте двумерный массив 10x3, заполненный случайными значениями. В каждой строке выберите значение, наиболее близкое к 0.5.



In [5]:
a = np.random.randn(10, 3)
print(a)
b = np.argmin(abs(a - 0.5), axis = 1)
for i in range(0, 9):
   print(a[i][b[i]])


[[ 0.38104719 -1.19189983 -0.91188671]
 [ 1.59460593  0.64000476  1.04290986]
 [-0.59678108 -0.92495384  1.50302446]
 [-0.86247567 -0.14978141  0.09544671]
 [ 0.90604995  1.43156094  1.17801509]
 [ 0.22720422  1.55433899 -2.33269792]
 [ 0.65606512 -1.014815   -1.08265633]
 [ 2.08997809 -1.14367969  0.76422885]
 [ 0.68601535  0.2999085  -1.56679796]
 [ 0.47121956  1.80642077 -3.00551453]]
0.3810471895038589
0.6400047559312109
1.5030244573089673
0.09544671285338381
0.9060499505130792
0.22720421960227113
0.6560651215750504
0.7642288459532696
0.6860153501584009


3.Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [9]:
a = np.random.randn(6, 6)
print(a, a[2])

b = np.max(a, axis = 0)
c = np.sum(a, axis = 1)
print(b, c)
for i in range(0, 5):
  print(c[i]/b[i])
   

[[ 0.30082934 -0.18670922 -0.86749674  1.38054828  0.17099182  0.25968475]
 [-2.09009951 -1.05437093  0.06939374  0.99075578  1.16304071 -0.84348362]
 [-1.71541788  0.57480422  0.59745718  1.98723331  0.05803409 -0.06158756]
 [ 0.89253226  0.799253    0.1006769   0.75428556  1.42626539 -0.33959144]
 [-0.10422188  0.92591358  0.28520641 -2.04858228  0.63826877  0.27119119]
 [ 0.45063591  0.54606337  0.07605245  0.28835413 -0.96312352  1.93833254]] [-1.71541788  0.57480422  0.59745718  1.98723331  0.05803409 -0.06158756]
[0.89253226 0.92591358 0.59745718 1.98723331 1.42626539 1.93833254] [ 1.05784824 -1.76476382  1.44052335  3.63342168 -0.03222421  2.33631488]
1.1852212921397371
-1.9059703458423065
2.411090523578518
1.828382034255046
-0.022593415198727703


4.












На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [7]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
max(x[i] for i in range(1, len(x)) if x[i - 1] == 0)


5

5.Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.


In [8]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])

for k in range(0, len(i)):
  x [i[k]] = x [i[k]] + 1
#x[i] = x[i] + 1
print( x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


6. Сколько вы можете предложить способов округлить значения в массиве до ближайшего целого?

In [ ]:
a = np.random.randn(10)
print(a)
np.around(a)

[ 0.04769888  0.03986131 -0.7687813  -0.11107814 -0.63499085 -0.75572883
 -0.38767541  1.95323209  0.82743609  0.44901012]


array([ 0.,  0., -1., -0., -1., -1., -0.,  2.,  1.,  0.])

7. Написать функцию, реализующую алгоритм k-means.

Входом в функцию является

массив NxM, где N - число объектов, M - число признаков объекта
k - число кластеров
max_iter - максимальное число итераций
theshold - критерий остановки (если на очередной итерации метода суммарное квадратичное отклонение изменяется меньше, чем на theshold, итерации прекращаются)
Выход:

массив длины N, содержащий индексы кластеров от 0 до k-1
суммарное квадратичное отклонение для полученного разбиения на кластеры

In [16]:
def dist(arr_1, arr_2):#вычисляет расстояние от каждой точки до каждого центра возвращает массив размера N*k
  d = np.array((N, k))
  for i in range(0, N):
      for j in range(0, k):
          d[i][j] = np.sqrt(np.sum(np.square(arr_1[i] - arr_2[j])))


In [ ]:
def quad_dev(centr, arr): #суммарное среднек......
  return np.sum(np.sum(np.sum((np.square(centr[i] - arr[j]))for j in res if res[j] == i)  for i in range(0, k))#??????

In [18]:
def kmeans(arr, k, max_iter, theshold):
#выбиарем центры кластеров
  res = np.array(N)#массив содержащий индексы кластеров
  centr = np.random.randn ((k, M))
  dev_1 = quad_dev(centr, arr)

  for i in range(0, max_iter):
      res = argmin(dist(arr, centr),axis=1) #распределяем элементы по кластерам #минимум в строке 
      for i in range(0, k): #новые центры масс
          mask = res == i 
          centr[i] = sum(arr, mask, axis=1 )/mask.size #складываем строчки поэлементно - находим новые центры 
          dev_2 = quad_dev(centr, arr)
      if abs(dev_1 - dev_2) < theshold  #критерий остановки
          return(centr, dev_2)
      else dev_1 = dev_2